/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo { 'instagramHandle' : string, 'email' : string }
export interface CustomOrder {
  'customerName' : string,
  'deliveryAddress' : string,
  'customizationDetails' : string,
  'productName' : string,
  'preferredDeliveryDate' : string,
  'timestamp' : Time,
  'quantity' : bigint,
  'phoneNumber' : string,
  'instagramId' : string,
}
export interface Product { 'name' : string, 'price' : bigint }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCustomOrders' : ActorMethod<[], Array<CustomOrder>>,
  'getAllProducts' : ActorMethod<[], Array<[string, Product]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCustomOrder' : ActorMethod<
    [string, string, string, string, string, bigint, string, string],
    string
  >,
  'updateContactInfo' : ActorMethod<[string, string], undefined>,
  'updateProductPrice' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];